# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_remove_footballplayers_footballclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballplayers',
            name='footballclub',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='football.footballClub'),
            preserve_default=False,
        ),
    ]
