# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_footballplayers_footballclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='clubBadge',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
