# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_footballclub_clubbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballplayers',
            name='playerStrengths',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='footballplayers',
            name='playerWeakness',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='footballplayers',
            name='shirtNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='clubBadge',
            field=models.FileField(upload_to=b''),
        ),
    ]
