# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0008_auto_20160827_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
